---
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
pool:
  name: 'Azure Pipelines'
  vmImage: ubuntu-latest

trigger:
  - main

extends:
  template: ./templates/demoparameters.yaml
  parameters:
    branch: 'master'
    agentvmImage: 'ubuntu-18.04'
    jdkVersion: '1.8'  
