---
pool: 
  name: "Azure Pipelines"
  vmImage: ubuntu-latest

trigger:
  - main
  
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 16.x
    displayName: 'Install Node.js'
  - task: Npm@1
    inputs:
      command: install
    displayName: 'npm install' 
  - task: Npm@1
    inputs:
      command: run build
    displayName: 'npm run build'