---
pool: 
  name: "Azure Pipelines"
  vmImage: 'ubuntu-latest'

trigger: 
  - main

stages:
  - stage: Build and Integration
    displayName: CI-petclinic
    jobs:
      - job: mavenjob
        displayName: maven
        steps: 
          - task: Maven@3
            inputs:
              mavenPOMFile: 'pom.xml'
              goals: 'package'
              publishJUnitResults: true
              testResultsFiles: '**/surefile-reports/TEST-*.xml'
              jdkVersionOption: '1.17'
            


---
pool:
  name: "Azure Pipeline"
  vmImage: "ubuntu-latest"            

trigger:
  schedules:
    - cron: "0 21 * * 1-5"
      always: false
steps: 
  task: maven@4
  inputs: 
    mavenPOMFile: yes
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    jdkVersionOption: '1.8'
          