---
pool: 
  name: "Azure Pipelines"
  vmImage: 'ubuntu-latest'

trigger: 
  - main

stages:
  - stage: Build and Integration
    displayName: CI-petclinic
    jobs:
      - job: mavenjob
        displayName: maven
        steps: 
          - task: Maven@3
            inputs:
              mavenPOMFile: 'pom.xml'
              goals: 'package'
              publishJUnitResults: true
              testResultsFiles: '**/surefile-reports/TEST-*.xml'
              jdkVersionOption: '1.17'
            