---
pool:
  name: 'Azure Pipelines'
  vmImage: ubuntu-latest

trigger:
  - main

extends:
  template: ./templates/demoparameters.yaml
  parameters:
    branch: 'master'
    agentvmImage: 'ubuntu-18.04'
    jdkVersion: '1.8'    