---
- name: installing the kafka on ubuntu 20.04
  hosts: all
  become: yes
  tasks:
    - name: install the java on ubuntu
      ansible.builtin.apt:
        name: openjdk-11-jre-headless
        update_cache: yes
        state: present
    - name: creating the directory kafka-server
      ansible.builtin.file: 
        path: /usr/local/kafka-server
        state: directory
    - name: download and install the apache kafka 
      ansible.builtin.unarchive:
        src: https://dlcdn.apache.org/kafka/3.0.0/kafka_2.13-3.4.0.tgz
        dest: /usr/local/kafka-server
    - name: copy the zookeeper file
      ansible.builtin.copy: 
        src: zookeeper.service
        dest: /etc/systemd/system/zookeeper.service  
    - name: copy the kafka server file
      ansible.builtin.copy: 
        src: kafka.service 
        dest: /etc/systemd/system/kafka.service 
    - name: start the zookeeper and kafka 
      ansible.builtin.systemd:
        name: kafka zookeeper
        daemon_reload: yes
        enabled: yes
        state: started             